### ISSUE TITLE
OSError: Read-Only file system: '/assets'

### ISSUE THREAD

**Issue by joe-toolhouse** [seanthegeek/wp2jekyll#2]
Running the script on a mac, i get an error trying to write to `/assets`. This is coming from line `:105`, and works if i change it to a relative path instead of the root directory.  See pull request for my fix.

**Comment by joe-toolhouse** [comment]
![Screenshot 2024-11-25 at 9 33 24 AM](https://github.com/user-attachments/assets/20c44dd9-ff65-4747-97dd-60aff1171915)

**Comment by seanthegeek** [comment]
I think I came up with a solution. Try the version that I just committed to the repository.
